force-app/main/default/objects/MV_Room__c/MV_Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>
 

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Available__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if a room is ready to book.</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Occupied__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room is occupied.</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_RoomNumber__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomNumber__c</fullName>
    <description>Field to indicate the room number.</description>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_SEL_Type__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Type__c</fullName>
    <description>Field to indicate room type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_RoomType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_RoomType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Double</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>President Suite</fullName>
    </customValue>
    <description>This picklist contains all room types that a hotel could have.</description>
    <masterLabel>Room Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RoomAvailableScheldule.cls
public with sharing class RoomAvailableScheldule implements Schedulable {
    public void execute(SchedulableContext ctx) {
        list<MV_Room__c> endOfRentListUpdate = new List<MV_Room__c>();
        list<MV_Room__c> startOfRentListUpdate = new List<MV_Room__c>();

        list<MV_Room__c> endOfRent = [SELECT Id, Name, MV_FLG_Available__c, MV_SEL_Type__c, MV_NUM_RoomNumber__c FROM MV_Room__c WHERE MV_FLG_Occupied__c = TRUE AND ID IN (SELECT MV_Room__c FROM Reservation__c WHERE Check_out_Date__c = TODAY)];

        list<MV_Room__c> startOfRent = [SELECT Id, Name, MV_FLG_Available__c, MV_SEL_Type__c, MV_NUM_RoomNumber__c FROM MV_Room__c WHERE MV_FLG_Occupied__c = TRUE AND ID IN (SELECT MV_Room__c FROM Reservation__c WHERE Check_In_Date__c = TODAY)];

        if (endOfRent.size() > 0) {
            for (MV_Room__c r : endOfRent) {
                r.MV_FLG_Available__c = true;
                r.MV_FLG_Occupied__c = false;

                endOfRentListUpdate.add(r);
            }
        }

        if (startOfRent.size() > 0) {
            for (MV_Room__c r : startOfRent) {
                r.MV_FLG_Available__c = false;
                r.MV_FLG_Occupied__c = true;

                startOfRentListUpdate.add(r);
            }
        }

        update endOfRentListUpdate;
        update startOfRentListUpdate;
    }
}