force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_SEL_Country__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Country__c</fullName>
    <defaultValue>&quot;Unallocated&quot;</defaultValue>
    <description>This field indicates the country where the hotel is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_City__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_City__c</fullName>
    <description>Indicates the city where the hotel is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Latvia</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuania</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Romania</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>Unallocated</fullName>
    </customValue>
    <description>This picklist contains all countries where hotels can be located.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/hotelControllerTest.cls
@isTest
public with sharing class hotelControllerTest {
    @TestSetup
    static void makeData() {
        MV_Hotel__c h1 = new MV_Hotel__c(Name = 'Test Hotel', MV_TXT_City__c = 'Test City', MV_SEL_Country__c = 'Poland');
        insert h1;
    }

    static testMethod void test1() {
        hotelController.roomNumber();

        list<AggregateResult> cList = hotelController.countryList();
        system.assertEquals(cList.size(), 1);

        list<AggregateResult> cList2 = hotelController.CityList('Poland');
        system.debug(cList2);

        Object city = cList2[0].get('MV_TXT_City__c');
        system.assertEquals(city, 'Test City');

        list<AggregateResult> cListnull = hotelController.CityList('');
        system.debug(cListnull);

        Object citynull = cListnull[0].get('MV_TXT_City__c');
        system.assertEquals(citynull, 'Test City');
    }

    static testMethod void test2() {
        list<AggregateResult> hotelList = hotelController.hotelList('Poland', 'Test City');
    }
}