force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_FOR_RatingStars__c.field-meta.xml
<CustomField>
    <fullName>MV_FOR_RatingStars__c</fullName>
    <description>Image representation of MV_SEL_Rating__c field.</description>
    <formula>IMAGE( 
CASE( MV_SEL_Rating__c, 
&quot;1&quot;, &quot;/img/samples/stars_100.gif&quot;,
&quot;2&quot;, &quot;/img/samples/stars_200.gif&quot;,
&quot;3&quot;, &quot;/img/samples/stars_300.gif&quot;, 
&quot;4&quot;, &quot;/img/samples/stars_400.gif&quot;, 
&quot;5&quot;, &quot;/img/samples/stars_500.gif&quot;, 
&quot;/img/samples/stars_000.gif&quot;), 
&quot;rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating Stars</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_RoomsOutOfService__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomsOutOfService__c</fullName>
    <description>This field indicates the number of rooms out of service.</description>
    <label>Rooms out of service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_TotalRentedRooms__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_TotalRentedRooms__c</fullName>
    <description>This field indicates the number of total rented rooms.</description>
    <label>Total Rented Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HotelDataUpdateQuable.cls
public class HotelDataUpdateQuable {

    @future
    public static void HotelDataCountUpdate(list<Id> recordIds) {

    map<Id,Integer> HotelServiceCT = new map<id,Integer>();
    map<Id,Integer> HotelAvialableCT = new map<id,Integer>();
    map<Id,Integer> HotelRentedleCT = new map<id,Integer>();

    list<MV_Hotel__c> HotelUpdateList = new list<MV_Hotel__c>();


    //Prepare DATA

    AggregateResult[] aggService = [SELECT MV_Hotel__c , count(Id) ct from Room__c WHERE MV_Hotel__c IN: recordIds  AND Service__c = TRUE GROUP BY MV_Hotel__c];

    AggregateResult[] aggAvailable = [SELECT MV_Hotel__c , count(Id) ct from Room__c WHERE MV_Hotel__c IN: recordIds  AND service__c != TRUE AND occupied__c != TRUE  GROUP BY MV_Hotel__c];

    AggregateResult[] aggOccupied = [SELECT MV_Hotel__c , count(Id) ct from Room__c WHERE MV_Hotel__c IN: recordIds  AND occupied__c = TRUE  GROUP BY MV_Hotel__c];


    for(AggregateResult ar : aggService){
        HotelServiceCT.put((Id)ar.get('MV_Hotel__c'),(Integer)ar.get('ct'));
    }
    for(AggregateResult arAvailable : aggAvailable){
        HotelAvialableCT.put((Id)arAvailable.get('MV_Hotel__c'),(Integer)arAvailable.get('ct'));
    }
     for(AggregateResult arOccupied : aggOccupied){
        HotelRentedleCT.put((Id)arOccupied.get('MV_Hotel__c'),(Integer)arOccupied.get('ct'));
    }

    for(MV_Hotel__c h: [SELECT Id,MV_NUM_RoomsOutOfService__c FROM MV_Hotel__c WHERE Id In: recordIds]){

        if(aggService.size() == 0){
        h.MV_NUM_RoomsOutOfService__c = 0;
        }
        else{
            h.MV_NUM_RoomsOutOfService__c = HotelServiceCT.get(h.Id);
        }
        h.MV_FOR_RatingStars__c = HotelAvialableCT.get(h.Id);
        h.MV_NUM_TotalRentedRooms__c = HotelRentedleCT.get(h.Id);

        HotelUpdateList.add(h);

    }
    update HotelUpdateList;


    }
}