force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_SEL_Country__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Country__c</fullName>
    <defaultValue>&quot;Unallocated&quot;</defaultValue>
    <description>This field indicates the country where the hotel is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_City__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_City__c</fullName>
    <description>Indicates the city where the hotel is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/MV_Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>
 

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_MaxNumberGuests__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_MaxNumberGuests__c</fullName>
    <description>Field to indicate the maximum number of guests in this room.</description>
    <label>Max Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_RoomNumber__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomNumber__c</fullName>
    <description>Field to indicate the room number.</description>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_SEL_Type__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Type__c</fullName>
    <description>Field to indicate room type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_RoomType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Latvia</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuania</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Romania</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>Unallocated</fullName>
    </customValue>
    <description>This picklist contains all countries where hotels can be located.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MV_Core_RoomType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Double</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>President Suite</fullName>
    </customValue>
    <description>This picklist contains all room types that a hotel could have.</description>
    <masterLabel>Room Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/roomControllerTest.cls
@isTest
public with sharing class roomControllerTest {
    @TestSetup
    static void makeData() {
        MV_Hotel__c hotel = new MV_Hotel__c(Name = 'Test Hotel', MV_SEL_Country__c = 'Poland', MV_TXT_City__c = 'Wroclaw');
        insert hotel;

        MV_Room__c r1 = new MV_Room__c(Name = 'Test Single Room 1', MV_Hotel__c = hotel.Id, MV_NUM_MaxNumberGuests__c = 5);
        insert r1;

        MV_Room__c r2 = new MV_Room__c(Name = 'Test Single Room 2', MV_Hotel__c = hotel.Id, MV_NUM_MaxNumberGuests__c = 5, MV_SEL_Type__c = 'Double', MV_NUM_RoomNumber__c = 2);
        insert r2;
    }

    static testMethod void roomControllerTest() {
        //Test rooms with all data

        roomController.FILTERSAPEX filters = new roomController.FILTERSAPEX();

        filters.city = 'Wroclaw';
        filters.country = 'Poland';
        filters.startDate = '2022-08-24';
        filters.endDate = '2022-08-28';
        filters.numberOfGuests = '5';
        filters.rooms = new List<String>{ 'Double' };
        filters.hotel = 'Test Hotel';

        list<MV_Room__c> rTest = roomController.roomDisplayList(filters);

        //Test rooms without type data

        roomController.FILTERSAPEX filtersWithoutType = new roomController.FILTERSAPEX();

        filtersWithoutType.city = 'Wroclaw';
        filtersWithoutType.country = 'Poland';
        filtersWithoutType.numberOfGuests = '5';
        filtersWithoutType.hotel = 'Test Hotel';

        list<MV_Room__c> rTest2 = roomController.roomDisplayList(filtersWithoutType);

        //Test other return methods
        List<MV_Hotel__c> hList = [SELECT Id FROM MV_Hotel__c];

        list<MV_Room__c> roomList = roomController.roomList(hlist);
        list<MV_Room__c> available = roomController.availableRooms(hlist);
        list<MV_Room__c> occupied = roomController.occupiedRooms(hlist);
        list<MV_Room__c> endReservation = roomController.endReservation();
    }
}