force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_TotalRooms__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_TotalRooms__c</fullName>
    <description>This field indicates the total number of rooms.</description>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_SEL_Country__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Country__c</fullName>
    <defaultValue>&quot;Unallocated&quot;</defaultValue>
    <description>This field indicates the country where the hotel is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_City__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_City__c</fullName>
    <description>Indicates the city where the hotel is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/MV_Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>
 

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_AirCondition__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_AirCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicates if the room has air condition.</description>
    <label>Air Condition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Jacuzzi__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Jacuzzi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room has jacuzzi.</description>
    <label>Jacuzzi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_MiniBar__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_MiniBar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room has mini bar.</description>
    <label>Mini Bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_RoomNumber__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomNumber__c</fullName>
    <description>Field to indicate the room number.</description>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_SEL_Type__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Type__c</fullName>
    <description>Field to indicate room type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_RoomType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Latvia</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuania</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Romania</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>Unallocated</fullName>
    </customValue>
    <description>This picklist contains all countries where hotels can be located.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MV_Core_RoomType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Double</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>President Suite</fullName>
    </customValue>
    <description>This picklist contains all room types that a hotel could have.</description>
    <masterLabel>Room Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/roomMaintenanceTest.cls
@isTest
public with sharing class roomMaintenanceTest {
    @TestSetup
    static void makeData() {
        MV_Hotel__c testHotel = new MV_Hotel__c(Name = 'Test Hotel', MV_TXT_City__c = 'Wroclaw', MV_SEL_Country__c = 'Poland', MV_NUM_TotalRooms__c = 0);
        insert testHotel;
    }

    static testMethod void roomMaintenanceTest() {
        list<MV_Hotel__c> hList = [SELECT Id, Name FROM MV_Hotel__c];
        roomMaintenance.generateRooms(hList);

        list<MV_Room__c> rommList = [SELECT Id, Name, MV_FLG_Jacuzzi__c, MV_SEL_Type__c, MV_FLG_MiniBar__c, MV_FLG_AirCondition__c, MV_NUM_RoomNumber__c, MV_Hotel__c FROM MV_Room__c];
        system.assertEquals(rommList.size(), 4);

        roomMaintenance.updateHotelRoomsCount(hList);

        list<MV_Hotel__c> hroom = [SELECT Id, Name, MV_NUM_TotalRooms__c FROM MV_Hotel__c];
        system.debug(hroom);

        system.assertEquals(hroom[0].MV_NUM_TotalRooms__c, 4);

        roomMaintenance.updateRoomNumbers(hList);

        AggregateResult[] ag = [SELECT MAX(MV_NUM_RoomNumber__c) maxNum, MIN(MV_NUM_RoomNumber__c) minNum FROM MV_Room__c];

        system.assertEquals(ag[0].get('maxNum'), 4);
        system.assertEquals(ag[0].get('minNum'), 1);
    }
}