force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_SEL_Country__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Country__c</fullName>
    <defaultValue>&quot;Unallocated&quot;</defaultValue>
    <description>This field indicates the country where the hotel is located.</description>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_City__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_City__c</fullName>
    <description>Indicates the city where the hotel is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_PostalCode__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_PostalCode__c</fullName>
    <description>This field stores the postal code of the hotel&apos;s location.</description>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_Street__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_Street__c</fullName>
    <description>This fields indicates the street where the hotel is located.</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Croatia</fullName>
    </customValue>
    <customValue>
        <fullName>Cyprus</fullName>
    </customValue>
    <customValue>
        <fullName>Czech Republic</fullName>
    </customValue>
    <customValue>
        <fullName>Denmark</fullName>
    </customValue>
    <customValue>
        <fullName>Estonia</fullName>
    </customValue>
    <customValue>
        <fullName>Finland</fullName>
    </customValue>
    <customValue>
        <fullName>France</fullName>
    </customValue>
    <customValue>
        <fullName>Germany</fullName>
    </customValue>
    <customValue>
        <fullName>Greece</fullName>
    </customValue>
    <customValue>
        <fullName>Hungary</fullName>
    </customValue>
    <customValue>
        <fullName>Ireland</fullName>
    </customValue>
    <customValue>
        <fullName>Italy</fullName>
    </customValue>
    <customValue>
        <fullName>Latvia</fullName>
    </customValue>
    <customValue>
        <fullName>Lithuania</fullName>
    </customValue>
    <customValue>
        <fullName>Luxembourg</fullName>
    </customValue>
    <customValue>
        <fullName>Malta</fullName>
    </customValue>
    <customValue>
        <fullName>Netherlands</fullName>
    </customValue>
    <customValue>
        <fullName>Poland</fullName>
    </customValue>
    <customValue>
        <fullName>Portugal</fullName>
    </customValue>
    <customValue>
        <fullName>Romania</fullName>
    </customValue>
    <customValue>
        <fullName>Slovakia</fullName>
    </customValue>
    <customValue>
        <fullName>Slovenia</fullName>
    </customValue>
    <customValue>
        <fullName>Spain</fullName>
    </customValue>
    <customValue>
        <fullName>Sweden</fullName>
    </customValue>
    <customValue>
        <fullName>Unallocated</fullName>
    </customValue>
    <description>This picklist contains all countries where hotels can be located.</description>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HotelMapMarker.cls
public with sharing class HotelMapMarker implements IMapMarker{

    public list<sObject> getRecords(){

        return [SELECT Id,Name,MV_SEL_Country__c,MV_TXT_City__c,MV_TXT_PostalCode__c,MV_TXT_Street__c from MV_Hotel__c];
    }

    public list<Object> wrapRecordForUI(list<sObject> sObjectRecords){

        list<MapMarker> mapMarkersList = new list<MapMarker>();

            for(MV_Hotel__c h: (list<MV_Hotel__c>)sObjectRecords){

            MapMarker marker = new MapMarker();
           // MapLocation location = new MapLocation();

            marker.location.City = h.MV_TXT_City__c;
            marker.location.Country = h.MV_SEL_Country__c;
            marker.location.Street = h.MV_TXT_Street__c;
            marker.location.PostalCode = h.MV_TXT_PostalCode__c;


            marker.description = 'This is Hotel description.';
            marker.title = h.Name;
            //marker.location = location;

            mapMarkersList.add(marker);

            }

            return mapMarkersList;


    }


}