force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_FOR_RatingStars__c.field-meta.xml
<CustomField>
    <fullName>MV_FOR_RatingStars__c</fullName>
    <description>Image representation of MV_SEL_Rating__c field.</description>
    <formula>IMAGE( 
CASE( MV_SEL_Rating__c, 
&quot;1&quot;, &quot;/img/samples/stars_100.gif&quot;,
&quot;2&quot;, &quot;/img/samples/stars_200.gif&quot;,
&quot;3&quot;, &quot;/img/samples/stars_300.gif&quot;, 
&quot;4&quot;, &quot;/img/samples/stars_400.gif&quot;, 
&quot;5&quot;, &quot;/img/samples/stars_500.gif&quot;, 
&quot;/img/samples/stars_000.gif&quot;), 
&quot;rating&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating Stars</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_RoomsOutOfService__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomsOutOfService__c</fullName>
    <description>This field indicates the number of rooms out of service.</description>
    <label>Rooms out of service</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_TotalRentedRooms__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_TotalRentedRooms__c</fullName>
    <description>This field indicates the number of total rented rooms.</description>
    <label>Total Rented Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_TotalRooms__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_TotalRooms__c</fullName>
    <description>This field indicates the total number of rooms.</description>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Hotel__c/fields/MV_TXT_City__c.field-meta.xml
<CustomField>
    <fullName>MV_TXT_City__c</fullName>
    <description>Indicates the city where the hotel is located.</description>
    <label>City</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/MV_Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>
 

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Available__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if a room is ready to book.</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Occupied__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Occupied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room is occupied.</description>
    <label>Occupied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_ServiceRequired__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_ServiceRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room required service</description>
    <label>Service Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_RoomNumber__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomNumber__c</fullName>
    <description>Field to indicate the room number.</description>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/roomTriggerAfterUpdateTest.cls
@IsTest
public class roomTriggerAfterUpdateTest {
    static testMethod void testUnit() {
        //Create hotel to test
        MV_Hotel__c h = new MV_Hotel__c(Name = 'tst', MV_TXT_City__c = 'Nibylandia', MV_NUM_TotalRooms__c = 5, MV_FOR_RatingStars__c = 5);

        insert h;

        MV_Hotel__c h2 = new MV_Hotel__c(Name = 'tst2', MV_TXT_City__c = 'Nibylandia2', MV_NUM_TotalRooms__c = 5, MV_FOR_RatingStars__c = 5);

        insert h2;

        list<MV_Room__c> rUpdate = new List<MV_Room__c>();

        // create 160 rooms test
        for (integer i = 0; i < 160; i++) {
            MV_Room__c r = new MV_Room__c(Name = 'test', MV_NUM_RoomNumber__c = i + 1, MV_Hotel__c = h.Id, MV_FLG_Available__c = true);

            rUpdate.add(r);
        }
        MV_Room__c r2 = new MV_Room__c(Name = 'test', MV_NUM_RoomNumber__c = 161, MV_Hotel__c = h.Id, MV_FLG_ServiceRequired__c = true);

        rUpdate.add(r2);

        MV_Room__c r3 = new MV_Room__c(Name = 'test', MV_NUM_RoomNumber__c = 162, MV_Hotel__c = h.Id, MV_FLG_Occupied__c = true);

        rUpdate.add(r3);

        // Performe Test
        test.startTest();

        insert rUpdate;

        list<MV_Room__c> UpdateList = [SELECT Id, Name, MV_NUM_RoomNumber__c, MV_Hotel__c, MV_FLG_ServiceRequired__c, MV_FLG_Occupied__c, MV_FLG_Available__c FROM MV_Room__c];
        list<MV_Room__c> updateListFinal = new List<MV_Room__c>();

        for (MV_Room__c r : UpdateList) {
            if (r.MV_NUM_RoomNumber__c <= 50) {
                r.MV_FLG_ServiceRequired__c = true;
                r.MV_FLG_Available__c = false;
                updateListFinal.add(r);
            } else if (r.MV_NUM_RoomNumber__c > 50 && r.MV_NUM_RoomNumber__c <= 80) {
                r.MV_FLG_Available__c = true;
                r.MV_FLG_Occupied__c = false;
                updateListFinal.add(r);
            } else if (r.MV_NUM_RoomNumber__c == 161) {
                r.MV_FLG_Available__c = true;
                r.MV_FLG_Occupied__c = false;
                r.MV_FLG_ServiceRequired__c = false;
                updateListFinal.add(r);
            } else if (r.MV_NUM_RoomNumber__c == 162) {
                r.MV_FLG_Available__c = true;
                r.MV_FLG_Occupied__c = false;
                r.MV_FLG_ServiceRequired__c = false;
                updateListFinal.add(r);
            } else {
                r.MV_FLG_Available__c = false;
                r.MV_FLG_Occupied__c = true;
                updateListFinal.add(r);
            }
        }
        update updateListFinal;

        Test.stopTest();

        MV_Hotel__c hotelData = [SELECT Id, MV_NUM_RoomsOutOfService__c, MV_FOR_RatingStars__c, MV_NUM_TotalRentedRooms__c FROM MV_Hotel__c WHERE Name = 'tst'];
        system.debug(hotelData);

        system.assertEquals(32, hotelData.MV_FOR_RatingStars__c);
        system.assertEquals(50, hotelData.MV_NUM_RoomsOutOfService__c);
    }
}