force-app/main/default/objects/MV_Hotel__c/MV_Hotel__c.object-meta.xml
<CustomObject>
    <description>All hotels managed by corporation.</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MV_Hotel__c/fields/MV_NUM_TotalRooms__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_TotalRooms__c</fullName>
    <description>This field indicates the total number of rooms.</description>
    <label>Total Rooms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/MV_Room__c.object-meta.xml
<CustomObject>
    <description>Rooms available in the Hotel.</description>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>
 

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_AirCondition__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_AirCondition__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicates if the room has air condition.</description>
    <label>Air Condition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Available__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if a room is ready to book.</description>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_Jacuzzi__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_Jacuzzi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room has jacuzzi.</description>
    <label>Jacuzzi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_FLG_MiniBar__c.field-meta.xml
<CustomField>
    <fullName>MV_FLG_MiniBar__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to indicate if the room has mini bar.</description>
    <label>Mini Bar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_MDR_Hotel__c.field-meta.xml
<CustomField>
    <fullName>MV_MDR_Hotel__c</fullName>
    <description>Master Hotel record.</description>
    <label>Hotel</label>
    <referenceTo>MV_Hotel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_MaxNumberGuests__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_MaxNumberGuests__c</fullName>
    <description>Field to indicate the maximum number of guests in this room.</description>
    <label>Max Number of Guests</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_NUM_RoomNumber__c.field-meta.xml
<CustomField>
    <fullName>MV_NUM_RoomNumber__c</fullName>
    <description>Field to indicate the room number.</description>
    <label>Room Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_SEL_Type__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_Type__c</fullName>
    <description>Field to indicate room type.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_RoomType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MV_Room__c/fields/MV_URL_Photo__c.field-meta.xml
<CustomField>
    <fullName>MV_URL_Photo__c</fullName>
    <description>Field to show the photo of the room.</description>
    <label>Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_RoomType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Single</fullName>
    </customValue>
    <customValue>
        <fullName>Double</fullName>
    </customValue>
    <customValue>
        <fullName>King</fullName>
    </customValue>
    <customValue>
        <fullName>President Suite</fullName>
    </customValue>
    <description>This picklist contains all room types that a hotel could have.</description>
    <masterLabel>Room Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/roomMaintenance.cls
public class roomMaintenance {
    public class roomType {
        String name;
        String url;
    }

    public static void generateRooms(list<MV_Hotel__c> hotelList) {
        //Prepare data
        list<MV_Hotel__c> queryList = [SELECT Id, Name FROM MV_Hotel__c WHERE Id IN :hotelList];
        //Create list to upload
        list<MV_Room__c> uploadList = new List<MV_Room__c>();
        //Available rooms

        list<String> roomTypes = new List<String>{ 'Single', 'Double', 'King', 'President Suite' };

        list<roomType> roomList = new List<roomType>();

        for (Integer i = 1; i <= roomTypes.size(); i++) {
            roomType r = new roomType();
            r.name = roomTypes[i - 1];
            r.url = Consts.ROOM_IMAGE.IMAGE_SOURCE.ImageUrl + '/photo' + Integer.valueof((1 + Math.random() * 10)) + '.jpg';
            roomList.add(r);
        }

        for (MV_Hotel__c h : queryList) {
            for (Integer i = 1; i <= roomList.size(); i++) {
                MV_Room__c ht = new MV_Room__c(
                    MV_Hotel__c = h.Id,
                    Name = roomList[i - 1].name + ' Room ' + h.Name,
                    MV_SEL_Type__c = roomList[i - 1].name,
                    MV_FLG_MiniBar__c = true,
                    MV_FLG_Available__c = true,
                    MV_FLG_AirCondition__c = true,
                    MV_NUM_RoomNumber__c = i,
                    MV_FLG_Jacuzzi__c = roomList[i - 1].name == 'President Suite' ? true : false,
                    MV_URL_Photo__c = roomList[i - 1].url,
                    MV_NUM_MaxNumberGuests__c = roomList[i - 1].name == 'President Suite' ? 5 : roomList[i - 1].name == 'King' ? 4 : roomList[i - 1].name == 'Double' ? 2 : 1
                );
                uploadList.add(ht);
            }
        }
        insert uploadList;
    }

    public static void generateRooms(String hotelId) {
        //Prepare data
        list<MV_Hotel__c> queryList = [SELECT Id, Name FROM MV_Hotel__c WHERE Id = :hotelId];
        //Create list to upload
        list<MV_Room__c> uploadList = new List<MV_Room__c>();
        //Available rooms

        list<String> roomTypes = new List<String>{ 'Single', 'Double', 'King', 'President Suite' };

        list<roomType> roomList = new List<roomType>();

        for (Integer i = 1; i <= roomTypes.size(); i++) {
            roomType r = new roomType();
            r.name = roomTypes[i - 1];
            r.url = Consts.ROOM_IMAGE.IMAGE_SOURCE.ImageUrl + '/photo' + Integer.valueof((1 + Math.random() * 10)) + '.jpg';
            roomList.add(r);
        }

        for (MV_Hotel__c h : queryList) {
            for (Integer i = 1; i <= roomList.size(); i++) {
                MV_Room__c ht = new MV_Room__c(
                    MV_Hotel__c = h.Id,
                    Name = roomList[i - 1].name + ' Room ' + h.Name,
                    MV_SEL_Type__c = roomList[i - 1].name,
                    MV_FLG_MiniBar__c = true,
                    MV_FLG_Available__c = true,
                    MV_FLG_AirCondition__c = true,
                    MV_NUM_RoomNumber__c = i,
                    MV_FLG_Jacuzzi__c = roomList[i - 1].name == 'President Suite' ? true : false,
                    MV_URL_Photo__c = roomList[i - 1].url,
                    MV_NUM_MaxNumberGuests__c = roomList[i - 1].name == 'President Suite' ? 5 : roomList[i - 1].name == 'King' ? 4 : roomList[i - 1].name == 'Double' ? 2 : 1
                );
                uploadList.add(ht);
            }
        }
        insert uploadList;
    }

    public static void updateHotelRoomsCount(List<MV_Hotel__c> hotelList) {
        AggregateResult[] aggRooms = [SELECT MV_Hotel__c, count(Id) ct FROM MV_Room__c WHERE MV_Hotel__c IN :hotelList GROUP BY MV_Hotel__c];

        map<String, Integer> hotelwithRoomCount = new Map<String, Integer>();
        list<MV_Hotel__c> updateListHotels = new List<MV_Hotel__c>();

        for (AggregateResult agg : aggRooms) {
            hotelwithRoomCount.put(String.valueOf(agg.get('MV_Hotel__c')), Integer.valueOf(agg.get('ct')));
        }
        list<MV_Hotel__c> hotelsList = [SELECT ID, (SELECT Id FROM Rooms__r) FROM MV_Hotel__c WHERE id IN :hotelwithRoomCount.keySet()];

        for (MV_Hotel__c h : hotelsList) {
            h.MV_NUM_TotalRooms__c = hotelwithRoomCount.get(h.Id);
            updateListHotels.add(h);
        }
        update updateListHotels;
    }

    public static void updateRoomNumbers(List<MV_Hotel__c> hotelList) {
        AggregateResult[] aggRooms = [SELECT MV_Hotel__c, count(Id) ct FROM MV_Room__c WHERE MV_Hotel__c IN :hotelList GROUP BY MV_Hotel__c];

        map<String, Integer> hotelwithRoomCount = new Map<String, Integer>();
        list<MV_Room__c> updateListRoom = new List<MV_Room__c>();

        for (AggregateResult agg : aggRooms) {
            hotelwithRoomCount.put(String.valueOf(agg.get('MV_Hotel__c')), Integer.valueOf(agg.get('ct')));
        }

        list<MV_Hotel__c> hotelsList = [SELECT ID, (SELECT Id FROM Rooms__r) FROM MV_Hotel__c WHERE id IN :hotelwithRoomCount.keySet()];

        for (MV_Hotel__c h : hotelsList) {
            Integer roomNum = 1;
            for (MV_Room__c r : h.Rooms__r) {
                r.MV_NUM_RoomNumber__c = roomNum;
                updateListRoom.add(r);
                roomNum++;
            }
        }
        update updateListRoom;
    }
}