force-app/main/default/objects/Contact/fields/MV_PER_Discount__c.field-meta.xml
<CustomField>
    <fullName>MV_PER_Discount__c</fullName>
    <description>Field to indicate the discount that applies for a user.</description>
    <label>Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MV_SEL_CustomerType__c.field-meta.xml
<CustomField>
    <fullName>MV_SEL_CustomerType__c</fullName>
    <description>Field to classify users.</description>
    <inlineHelpText>VIP - 40% discount, access to spa, car discount,premium Wi-Fi
Standard - discount based on num of TTM Reservations.
Internal Employee - 70% discount + VIP</inlineHelpText>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MV_Core_CustomerType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/MV_Core_CustomerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>VIP</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <customValue>
        <fullName>Internal Employee</fullName>
    </customValue>
    <description>This picklist is used to categorize users or customers based on their status or relationship with the organization.</description>
    <masterLabel>Customer Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactTriggerHandler.cls
public with sharing class ContactTriggerHandler {


    public static void beforeUpdate(list<Contact> newContact, map<Id,contact> oldMap){


        list<contact> customerStatusRecalc = new list<contact>();

        for(contact c : newContact){

            if(c.MV_SEL_CustomerType__c != oldMap.get(c.Id).MV_SEL_CustomerType__c){

                system.debug('New Record != old record');

                customerStatusRecalc.add(c);
            }

        }

        if(!customerStatusRecalc.isEmpty()){

            system.debug(customerStatusRecalc);

       map<Id,contact> updatedContactsMap = new map<Id,Contact>(Guest_Service.discountCalculator(customerStatusRecalc));

       for(contact c :newContact){

        c.MV_PER_Discount__c = updatedContactsMap.get(c.Id).MV_PER_Discount__c;
        system.debug(updatedContactsMap.get(c.Id).MV_PER_Discount__c);

       }



        }

    }

}